return {
	METADATA=nil,
	{TYPE=21, VARIANT=12000, SUBTYPE=0, NAME="Ambiance", DIFFICULTY=1, WEIGHT=1, WIDTH=13, HEIGHT=7, SHAPE=1, METADATA=nil,
		{ISDOOR=true, GRIDX=-1, GRIDY=3, SLOT=0, EXISTS=true},
		{ISDOOR=true, GRIDX=6, GRIDY=-1, SLOT=1, EXISTS=true},
		{ISDOOR=true, GRIDX=6, GRIDY=7, SLOT=3, EXISTS=true},
		{ISDOOR=true, GRIDX=13, GRIDY=3, SLOT=2, EXISTS=true},
		{ISDOOR=false, GRIDX=0, GRIDY=0,
			{TYPE=33, VARIANT=2, SUBTYPE=0, WEIGHT=1, METADATA=nil},
		},
		{ISDOOR=false, GRIDX=12, GRIDY=0,
			{TYPE=33, VARIANT=2, SUBTYPE=0, WEIGHT=1, METADATA=nil},
		},
		{ISDOOR=false, GRIDX=6, GRIDY=3,
			{TYPE=5, VARIANT=100, SUBTYPE=0, WEIGHT=1, METADATA=nil},
		},
		{ISDOOR=false, GRIDX=0, GRIDY=6,
			{TYPE=33, VARIANT=2, SUBTYPE=0, WEIGHT=1, METADATA=nil},
		},
		{ISDOOR=false, GRIDX=12, GRIDY=6,
			{TYPE=33, VARIANT=2, SUBTYPE=0, WEIGHT=1, METADATA=nil},
		}
    }
}